<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\SysWatt.Core\SysWatt.Core.csproj" />
    <PackageReference Include="LibreHardwareMonitorLib" />
    <PackageReference Include="Hwinfo.SharedMemory.Net" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
</Project>
